### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by merglml** [Ilias-fmi/ACO#1]
Backtarget and Locator is shit

**Comment by merglml** [comment]
only backtarget is shit. locator is fixed

**Comment by PhilippGruber** [comment]
bei mir geht beides nicht.  das backtarget bleibt stur auf der selben Seite egal was in dem array drin steht (auch bei nichts) während der back Knopf des Browsers zumindest geht. 
Locator stimmen zwar die Begriffe aber wenn man draufklickt kommt eine Fehlermeldung
